name: Code Linting & Formatting
on: push

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/setup_poetry
      - run: poetry install --only test

      - run: poetry run ruff check --output-format github
      - run: poetry run ruff format --diff
